Repository googleinterns/stampify, pull requests merged in 2020-07, with the labels that each got.

#76 Improved summarization quality
  requirements.txt
  summarization/text_summarization.py
Labels: enhancement, needs review, priority: high, size: S

#84 Bugfix for text media matching
  summarization/text_media_matching/text_media_matcher.py
  tests/summarizer/test_text_media_matcher.py
Labels: bugfix, priority: high, quick merge, size : xS

#83 Add fix for web entity detection
  summarization/web_entity_detection.py
  tests/summarizer/test_image_description_retreiver.py
Labels: bugfix, needs review, priority: high, size: S

#72 Add Restful API for project
  api/assets/css/main.css
  api/assets/fonts/Montserrat-Regular.ttf
  api/server.py
  api/templates/index.html
  main.py
  requirements.txt
  stamp_generation/fonts/Roboto-Regular.ttf
  stamp_generation/stamp_generator.py
Labels: enhancement

#98 Added support for embedded content
  summarization/stamp_descriptors_for_embedded_content.json
  summarization/stamp_page_picking/max_cover_preprocessor.py
  summarization/summarizer_main.py
Labels: enhancement, needs review, priority: high, quick merge, size: S

#104 Fix pylint errors
  .pylintrc
  classification/classifier_main.py
  summarization/extractor_output_preprocessor.py
  summarization/incorrect_input.py
  summarization/stamp_page_picking/budgeted_max_cover_solver.py
  summarization/stamp_page_picking/max_cover_preprocessor.py
  summarization/stamp_page_picking/stamp_page_picker.py
  summarization/summarizer_main.py
  summarization/summarizer_output.py
  summarization/text_entity_detection.py
  summarization/text_media_matching/stable_matcher.py
  summarization/text_media_matching/text_media_matcher.py
  summarization/text_media_matching/text_media_matching_preprocessor.py
  summarization/text_summarization.py
  summarization/web_entity_detection.py
Labels: priority: high, size: M

#114 Add heuristic choosing based on Title topic plurality
  summarization/summarizer_main.py
Labels: Priority: medium, enhancement, help wanted, needs review, size: M

#105 Added functionality to separate title text
  data_models/text.py
  summarization/extractor_output_preprocessor.py
Labels: bugfix, priority: high, quick merge, size : xS

#102 (Bugfix) Added proper indexing to remove stamp page ordering errors
  stampifier.py
  summarization/extractor_output_preprocessor.py
  summarization/summarizer_main.py
  summarization/summarizer_output.py
  summarization/text_media_matching/text_media_matching_helper.py
  tests/summarizer/text_media_input_fetcher.py
Labels: bugfix, needs review, priority: high, quick merge, size: S

#79 Added interesting sequence picker
  summarization/stamp_page_picking/interesting_sequence_picker.py
  summarization/stamp_page_picking/scoring_utils.py
  summarization/stamp_page_picking/stamp_page_picker.py
  summarization/summarizer_main.py
Labels: enhancement, priority: low, size: L

#109 Fix broken urls
  data_models/website.py
  extraction/content_extractors/embedded_instagram_post_extractor.py
  extraction/content_extractors/embedded_youtube_video_extractor.py
  extraction/content_extractors/image_extractor.py
  extraction/content_extractors/text_extractor.py
  extraction/content_extractors/video_extractor.py
  extraction/utils/media_extraction_utils.py
  tests/test_extraction/extraction_test_inputs/image.html
  tests/test_extraction/extraction_test_inputs/video.html
  tests/test_extraction/test_extraction_utils.py
  tests/test_extraction/test_image_extractor.py
  tests/test_extraction/test_video_extraction.py
  utils/__init__.py
  utils/url_utils.py
Labels: help wanted, needs review, priority: high

#124 Added Heuristics to improve summarization quality of listed webpages
  classification/classifier_main.py
  data_models/text.py
  stampifier.py
  summarization/extractor_output_preprocessor.py
  summarization/stamp_page_picking/scoring_utils.py
  summarization/summarizer_main.py
  summarization/text_media_matching/text_media_matcher.py
  summarization/text_media_matching/text_media_matching_helper.py
Labels: bugfix, enhancement, needs review, priority: high, size: S

#126 Quoted content support
  classification/classifier_main.py
  data_models/contents.py
  data_models/preprocessed_contents.py
  data_models/quote.py
  stampifier.py
  summarization/extractor_output_preprocessor.py
  summarization/stamp_descriptors_for_embedded_content.json
  summarization/stamp_page_picking/scoring_utils.py
  summarization/summarizer_main.py
  summarization/summarizer_output.py
Labels: code restructure, enhancement, needs review, priority: high, size: L

#136 Added bugfix for repeated stamp page
  summarization/summarizer_main.py
  summarization/text_media_matching/text_media_matcher.py
  summarization/text_media_matching/text_media_matching_preprocessor.py
Labels: bugfix, priority: high, size: S

#141 Refactor stamp template
  stamp_generation/stamp_generator.py
  stamp_generation/stamp_templates/center_text_template.jj2
  stamp_generation/stamp_templates/embedded_instagram_post_template.jj2
  stamp_generation/stamp_templates/embedded_pinterest_pin_template.jj2
  stamp_generation/stamp_templates/embedded_tweet_template.jj2
  stamp_generation/stamp_templates/embedded_youtube_video_template.jj2
  stamp_generation/stamp_templates/first_page_template.jj2
  stamp_generation/stamp_templates/image_template.jj2
  stamp_generation/stamp_templates/last_page_template.jj2
  stamp_generation/stamp_templates/overlay_text_template.jj2
  stamp_generation/stamp_templates/quote_template.jj2
  stamp_generation/stamp_templates/stamp_base_template.jj2
  stamp_generation/stamp_templates/stamp_css.jj2
  stamp_generation/stamp_templates/stamp_template.html.jinja
  stamp_generation/stamp_templates/video_template.jj2
Labels: cla: yes, code restructure

#138 Update url_utils
  utils/url_utils.py
Labels: cla: yes

#137 Added bugfix for title/extra stamp page
  data_models/text.py
  summarization/stamp_page_picking/interesting_sequence_picker.py
  summarization/summarizer_main.py
Labels: cla: yes, priority: high, quick merge, size : xS

#142 Add loader for stamp-iframe
  api/assets/css/main.css
  api/assets/js/main.js
  api/templates/index.html
Labels: cla: yes

#143 Added usage of url util to convert https to http in image description retriever
  summarization/web_entity_detection.py
  tests/summarizer/test_image_description_retreiver.py
Labels: bugfix, cla: yes, needs review, priority: high, quick merge, size : xS

#140 Caption detection and Image color detection
  .github/workflows/python-app.yml
  data_models/image.py
  summarization/extractor_output_preprocessor.py
  summarization/summarizer_main.py
  summarization/web_entity_detection.py
  tests/summarizer/test_image_description_retreiver.py
  tests/summarizer/test_summarizer.py
Labels: cla: yes, enhancement, help wanted, priority: high, question, size: M, tests

#131 Initial Code cleanup / Code Refactoring
  classification/classifier.py
  data_models/summarizer_output.py
  error.py
  stampifier.py
  summarization/bad_request_error.py
  summarization/cover.py
  summarization/extractor_output_preprocessor.py
  summarization/incorrect_input.py
  summarization/sentence_with_attributes.py
  summarization/stamp_page_picking/max_cover_preprocessor.py
  summarization/stamp_page_picking/scoring_utils.py
  summarization/stamp_page_picking/stamp_page_picker.py
  summarization/summarizer.py
  summarization/text_entity_detection.py
  summarization/text_media_matching/text_media_matching_helper.py
  summarization/text_summarization.py
  summarization/web_entity_detection.py
  tests/summarizer/test_image_description_retreiver.py
  tests/summarizer/test_summarizer.py
  tests/summarizer/test_text_entity_retriever.py
  tests/summarizer/test_text_media_matching_helper.py
  tests/summarizer/text_media_input_fetcher.py
Labels: Priority: medium, cla: yes, code restructure, size: M

#144 Add option for having animations
  api/assets/css/main.css
  api/server.py
  api/templates/index.html
  main.py
  stamp_generation/stamp_generator.py
  stamp_generation/stamp_templates/overlay_text_template.jj2
  stampifier.py
Labels: cla: yes

#134 Fix logger
  api/server.py
  extraction/extractor.py
  main.py
  stamp_generation/stamp_generator.py
  stampifier.py
Labels: bugfix, cla: yes, quick merge, size : xS

#145 Add gradient as background for images
  api/assets/css/main.css
  api/templates/index.html
  stamp_generation/stamp_templates/image_template.jj2
  stamp_generation/stamp_templates/overlay_text_template.jj2
  stamp_generation/stamp_templates/quote_template.jj2
  stamp_generation/stamp_templates/stamp_base_template.jj2
  stamp_generation/stamp_templates/stamp_css.jj2
Labels: cla: yes

#147 Remove flask app secret key
  Dockerfile
  api/server.py
  run_server.py
Labels: cla: yes

#146 Minor bugfixes
  classification/classifier.py
  stampifier.py
  summarization/extractor_output_preprocessor.py
  summarization/stamp_page_picking/max_cover_preprocessor.py
  summarization/web_entity_detection.py
  tests/summarizer/test_image_description_retreiver.py
  utils/url_utils.py
Labels: bugfix, cla: yes, documentation, needs review, priority: high, quick merge, size : xS

#151 budgeted max cover bugfix
  summarization/stamp_page_picking/budgeted_max_cover_solver.py
Labels: cla: yes

#152 more minor fixes for budgeted max cover
  summarization/stamp_page_picking/budgeted_max_cover_solver.py
Labels: cla: yes

#148 Update ReadMe
  README.md
  api/server.py
  main.py
  stamp_generation/stamp_templates/overlay_text_template.jj2
Labels: cla: yes
