Repository googleinterns/stampify, pull requests merged in 2020-06, with the labels that each got.

#15 Added utilities and tests for text media matching
  classifier_and_summarizer/__init__.py
  classifier_and_summarizer/summarizer/__init__.py
  classifier_and_summarizer/summarizer/stable_matcher.py
  classifier_and_summarizer/summarizer/text_media_matcher.py
  requirements.txt
  tests/summmarizer/test_text_media_matching.py
Labels: enhancement

#7 Add module for text extraction
  extraction/data_models/text.py
  extraction/extractor.py
  extraction/text_extractor.py
  extraction/utils/string_utils.py
  tests/test_extraction/test_input.html
  tests/test_extraction/test_text_extractor.py
Labels: enhancement

#10 Add module for video extraction
  extraction/data_models/video.py
  extraction/extractor.py
  extraction/utils/media_extraction_utils.py
  extraction/video_extractor.py
  tests/test_extraction/test_video_extraction.py
  tests/test_extraction/video.html
Labels: enhancement

#13 Add module for image extraction
  extraction/data_models/image.py
  extraction/extractor.py
  extraction/image_extractor.py
  extraction/utils/media_extraction_utils.py
  tests/test_extraction/image.html
  tests/test_extraction/test_image_extractor.py
Labels: enhancement

#27 fix command line input method
  main.py
Labels: bug

#57 Added method to order stamp pages
  classifier_and_summarizer_main.py
Labels: quick merge, size: S

#61 Added end to end integration of all modules
  classifier_and_summarizer_main.py
  main.py
  stamp_generation/final_generated_stamp.html
  stamp_generation/stamp_generator.py
  summarization/extractor_output_preprocessor.py
  summarization/summarizer_main.py
  summarization/text_summarization.py
Labels: bugfix, enhancement, needs review, size: S

#68 Added text entity detection along with tests
  .github/workflows/python-app.yml
  README.md
  summarization/bad_request_error.py
  summarization/text_entity_detection.py
  summarization/web_entity_detection.py
  tests/summarizer/test_image_description_retreiver.py
  tests/summarizer/test_text_entity_retriever.py
  tests/summarizer/test_text_media_matching.py
Labels: enhancement, needs review, size: M, tests

#70 Added title media matching
  summarization/extractor_output_preprocessor.py
  summarization/summarizer_main.py
Labels: enhancement, needs review, question, size: S
